# Generated by Django 5.0.6 on 2024-05-28 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/usuarios', verbose_name='Imagen')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('overview', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('documentacion', models.FileField(null=True, upload_to='documento/proyecto', verbose_name='Documentacion')),
                ('destacado', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('Por Aprobar', 'Pendiente'), ('Proyecto Aprobado', 'Aprobado'), ('Proyecto Rechazado', 'Rechazado')], default='Por Aprobar', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.categoria', verbose_name='Categoria')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.persona', verbose_name='Persona relacionada')),
            ],
        ),
        migrations.CreateModel(
            name='Commentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentari', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('Fecha_post', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.proyecto')),
            ],
            options={
                'ordering': ['-Fecha_post'],
            },
        ),
    ]
