# Generated by Django 5.0.6 on 2024-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_t_fase_proyecto_t_gestion_t_semestre_t_tipo_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_proyectos',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
