# Generated by Django 5.0.6 on 2024-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_t_proyectos_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitar_proyectos', models.BooleanField(default=True, verbose_name='Habilitar Proyectos')),
            ],
        ),
    ]
