# Generated by Django 5.0.6 on 2024-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='fecha_fin_habilitacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Habilitación'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='fecha_inicio_habilitacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Habilitación'),
        ),
    ]
