# Generated by Django 5.0.6 on 2024-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_globalsettings_fecha_fin_habilitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_proyectos',
            name='Fecha_Fin_Subida',
        ),
        migrations.RemoveField(
            model_name='t_proyectos',
            name='Fecha_Inicio_Subida',
        ),
        migrations.RemoveField(
            model_name='t_proyectos',
            name='habilitado',
        ),
    ]
